---
abstract: 'DEPRECIATED use Plack::Middleware::TemplateToolkit'
author:
  - 'Leo Lapworth <LLAP@cuckoo.org>'
build_requires:
  Cwd: 0
  English: 0
  HTTP::Request: 0
  Path::Class: 0
  Plack::Builder: 0
  Plack::Middleware::ErrorDocument: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-TemplateToolkit
requires:
  Plack::Component: 0
  Plack::Request: 0.9901
  Plack::Util::Accessor: 0
  Template: 2
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Plack-App-TemplateToolkit
version: 0.06
